export const country =[
  {value:'Afganistan', label:'Afghanistan'},
{value:'Albania', label:'Albania'},
{value:'Algeria', label:'Algeria'},
{value:'American Samoa', label:'American Samoa'},
{value:'Andorra', label:'Andorra'},
{value:'Angola', label:'Angola'},
{value:'Anguilla', label:'Anguilla'},
{value:'Antigua & Barbuda', label:'Antigua & Barbuda'},
{value:'Argentina', label:'Argentina'},
{value:'Armenia', label:'Armenia'},
{value:'Aruba', label:'Aruba'},
{value:'Australia', label:'Australia'},
{value:'Austria', label:'Austria'},
{value:'Azerbaijan', label:'Azerbaijan'},
{value:'Bahamas', label:'Bahamas'},
{value:'Bahrain', label:'Bahrain'},
{value:'Bangladesh', label:'Bangladesh'},
{value:'Barbados', label:'Barbados'},
{value:'Belarus', label:'Belarus'},
{value:'Belgium', label:'Belgium'},
{value:'Belize', label:'Belize'},
{value:'Benin', label:'Benin'},
{value:'Bermuda', label:'Bermuda'},
{value:'Bhutan', label:'Bhutan'},
{value:'Bolivia', label:'Bolivia'},
{value:'Bonaire', label:'Bonaire'},
{value:'Bosnia & Herzegovina', label:'Bosnia & Herzegovina'},
{value:'Botswana', label:'Botswana'},
{value:'Brazil', label:'Brazil'},
{value:'British Indian Ocean Ter', label:'British Indian Ocean Ter'},
{value:'Brunei', label:'Brunei'},
{value:'Bulgaria', label:'Bulgaria'},
{value:'Burkina Faso', label:'Burkina Faso'},
{value:'Burundi', label:'Burundi'},
{value:'Cambodia', label:'Cambodia'},
{value:'Cameroon', label:'Cameroon'},
{value:'Canada', label:'Canada'},
{value:'Canary Islands', label:'Canary Islands'},
{value:'Cape Verde', label:'Cape Verde'},
{value:'Cayman Islands', label:'Cayman Islands'},
{value:'Central African Republic', label:'Central African Republic'},
{value:'Chad', label:'Chad'},
{value:'Channel Islands', label:'Channel Islands'},
{value:'Chile', label:'Chile'},
{value:'China', label:'China'},
{value:'Christmas Island', label:'Christmas Island'},
{value:'Cocos Island', label:'Cocos Island'},
{value:'Colombia', label:'Colombia'},
{value:'Comoros', label:'Comoros'},
{value:'Congo', label:'Congo'},
{value:'Cook Islands', label:'Cook Islands'},
{value:'Costa Rica', label:'Costa Rica'},
{value:'Cote DIvoire', label:'Cote DIvoire'},
{value:'Croatia', label:'Croatia'},
{value:'Cuba', label:'Cuba'},
{value:'Curaco', label:'Curacao'},
{value:'Cyprus', label:'Cyprus'},
{value:'Czech Republic', label:'Czech Republic'},
{value:'Denmark', label:'Denmark'},
{value:'Djibouti', label:'Djibouti'},
{value:'Dominica', label:'Dominica'},
{value:'Dominican Republic', label:'Dominican Republic'},
{value:'East Timor', label:'East Timor'},
{value:'Ecuador', label:'Ecuador'},
{value:'Egypt', label:'Egypt'},
{value:'El Salvador', label:'El Salvador'},
{value:'Equatorial Guinea', label:'Equatorial Guinea'},
{value:'Eritrea', label:'Eritrea'},
{value:'Estonia', label:'Estonia'},
{value:'Ethiopia', label:'Ethiopia'},
{value:'Falkland Islands', label:'Falkland Islands'},
{value:'Faroe Islands', label:'Faroe Islands'},
{value:'Fiji', label:'Fiji'},
{value:'Finland', label:'Finland'},
{value:'France', label:'France'},
{value:'French Guiana', label:'French Guiana'},
{value:'French Polynesia', label:'French Polynesia'},
{value:'French Southern Ter', label:'French Southern Ter'},
{value:'Gabon', label:'Gabon'},
{value:'Gambia', label:'Gambia'},
{value:'Georgia', label:'Georgia'},
{value:'Germany', label:'Germany'},
{value:'Ghana', label:'Ghana'},
{value:'Gibraltar', label:'Gibraltar'},
{value:'Great Britain', label:'Great Britain'},
{value:'Greece', label:'Greece'},
{value:'Greenland', label:'Greenland'},
{value:'Grenada', label:'Grenada'},
{value:'Guadeloupe', label:'Guadeloupe'},
{value:'Guam', label:'Guam'},
{value:'Guatemala', label:'Guatemala'},
{value:'Guinea', label:'Guinea'},
{value:'Guyana', label:'Guyana'},
{value:'Haiti', label:'Haiti'},
{value:'Hawaii', label:'Hawaii'},
{value:'Honduras', label:'Honduras'},
{value:'Hong Kong', label:'Hong Kong'},
{value:'Hungary', label:'Hungary'},
{value:'Iceland', label:'Iceland'},
{value:'Indonesia', label:'Indonesia'},
{value:'India', label:'India'},
{value:'Iran', label:'Iran'},
{value:'Iraq', label:'Iraq'},
{value:'Ireland', label:'Ireland'},
{value:'Isle of Man', label:'Isle of Man'},
{value:'Israel', label:'Israel'},
{value:'Italy', label:'Italy'},
{value:'Jamaica', label:'Jamaica'},
{value:'Japan', label:'Japan'},
{value:'Jordan', label:'Jordan'},
{value:'Kazakhstan', label:'Kazakhstan'},
{value:'Kenya', label:'Kenya'},
{value:'Kiribati', label:'Kiribati'},
{value:'Korea North', label:'Korea North'},
{value:'Korea Sout', label:'Korea South'},
{value:'Kuwait', label:'Kuwait'},
{value:'Kyrgyzstan', label:'Kyrgyzstan'},
{value:'Laos', label:'Laos'},
{value:'Latvia', label:'Latvia'},
{value:'Lebanon', label:'Lebanon'},
{value:'Lesotho', label:'Lesotho'},
{value:'Liberia', label:'Liberia'},
{value:'Libya', label:'Libya'},
{value:'Liechtenstein', label:'Liechtenstein'},
{value:'Lithuania', label:'Lithuania'},
{value:'Luxembourg', label:'Luxembourg'},
{value:'Macau', label:'Macau'},
{value:'Macedonia', label:'Macedonia'},
{value:'Madagascar', label:'Madagascar'},
{value:'Malaysia', label:'Malaysia'},
{value:'Malawi', label:'Malawi'},
{value:'Maldives', label:'Maldives'},
{value:'Mali', label:'Mali'},
{value:'Malta', label:'Malta'},
{value:'Marshall Islands', label:'Marshall Islands'},
{value:'Martinique', label:'Martinique'},
{value:'Mauritania', label:'Mauritania'},
{value:'Mauritius', label:'Mauritius'},
{value:'Mayotte', label:'Mayotte'},
{value:'Mexico', label:'Mexico'},
{value:'Midway Islands', label:'Midway Islands'},
{value:'Moldova', label:'Moldova'},
{value:'Monaco', label:'Monaco'},
{value:'Mongolia', label:'Mongolia'},
{value:'Montserrat', label:'Montserrat'},
{value:'Morocco', label:'Morocco'},
{value:'Mozambique', label:'Mozambique'},
{value:'Myanmar', label:'Myanmar'},
{value:'Nambia', label:'Nambia'},
{value:'Nauru', label:'Nauru'},
{value:'Nepal', label:'Nepal'},
{value:'Netherland Antilles', label:'Netherland Antilles'},
{value:'Netherlands', label:'Netherlands (Holland, Europe)'},
{value:'Nevis', label:'Nevis'},
{value:'New Caledonia', label:'New Caledonia'},
{value:'New Zealand', label:'New Zealand'},
{value:'Nicaragua', label:'Nicaragua'},
{value:'Niger', label:'Niger'},
{value:'Nigeria', label:'Nigeria'},
{value:'Niue', label:'Niue'},
{value:'Norfolk Island', label:'Norfolk Island'},
{value:'Norway', label:'Norway'},
{value:'Oman', label:'Oman'},
{value:'Pakistan', label:'Pakistan'},
{value:'Palau Island', label:'Palau Island'},
{value:'Palestine', label:'Palestine'},
{value:'Panama', label:'Panama'},
{value:'Papua New Guinea', label:'Papua New Guinea'},
{value:'Paraguay', label:'Paraguay'},
{value:'Peru', label:'Peru'},
{value:'Phillipines', label:'Philippines'},
{value:'Pitcairn Island', label:'Pitcairn Island'},
{value:'Poland', label:'Poland'},
{value:'Portugal', label:'Portugal'},
{value:'Puerto Rico', label:'Puerto Rico'},
{value:'Qatar', label:'Qatar'},
{value:'Republic of Montenegro', label:'Republic of Montenegro'},
{value:'Republic of Serbia', label:'Republic of Serbia'},
{value:'Reunion', label:'Reunion'},
{value:'Romania', label:'Romania'},
{value:'Russia', label:'Russia'},
{value:'Rwanda', label:'Rwanda'},
{value:'St Barthelemy', label:'St Barthelemy'},
{value:'St Eustatius', label:'St Eustatius'},
{value:'St Helena', label:'St Helena'},
{value:'St Kitts-Nevis', label:'St Kitts-Nevis'},
{value:'St Lucia', label:'St Lucia'},
{value:'St Maarten', label:'St Maarten'},
{value:'St Pierre & Miquelon', label:'St Pierre & Miquelon'},
{value:'St Vincent & Grenadines', label:'St Vincent & Grenadines'},
{value:'Saipan', label:'Saipan'},
{value:'Samoa', label:'Samoa'},
{value:'Samoa American', label:'Samoa American'},
{value:'San Marino', label:'San Marino'},
{value:'Sao Tome & Principe', label:'Sao Tome & Principe'},
{value:'Saudi Arabia', label:'Saudi Arabia'},
{value:'Senegal', label:'Senegal'},
{value:'Seychelles', label:'Seychelles'},
{value:'Sierra Leone', label:'Sierra Leone'},
{value:'Singapore', label:'Singapore'},
{value:'Slovakia', label:'Slovakia'},
{value:'Slovenia', label:'Slovenia'},
{value:'Solomon Islands', label:'Solomon Islands'},
{value:'Somalia', label:'Somalia'},
{value:'South Africa', label:'South Africa'},
{value:'Spain', label:'Spain'},
{value:'Sri Lanka', label:'Sri Lanka'},
{value:'Sudan', label:'Sudan'},
{value:'Suriname', label:'Suriname'},
{value:'Swaziland', label:'Swaziland'},
{value:'Sweden', label:'Sweden'},
{value:'Switzerland', label:'Switzerland'},
{value:'Syria', label:'Syria'},
{value:'Tahiti', label:'Tahiti'},
{value:'Taiwan', label:'Taiwan'},
{value:'Tajikistan', label:'Tajikistan'},
{value:'Tanzania', label:'Tanzania'},
{value:'Thailand', label:'Thailand'},
{value:'Togo', label:'Togo'},
{value:'Tokelau', label:'Tokelau'},
{value:'Tonga', label:'Tonga'},
{value:'Trinidad & Tobago', label:'Trinidad & Tobago'},
{value:'Tunisia', label:'Tunisia'},
{value:'Turkey', label:'Turkey'},
{value:'Turkmenistan', label:'Turkmenistan'},
{value:'Turks & Caicos Is', label:'Turks & Caicos Is'},
{value:'Tuvalu', label:'Tuvalu'},
{value:'Uganda', label:'Uganda'},
{value:'United Kingdom', label:'United Kingdom'},
{value:'Ukraine', label:'Ukraine'},
{value:'United Arab Erimates', label:'United Arab Emirates'},
{value:'United States of America', label:'United States of America'},
{value:'Uraguay', label:'Uruguay'},
{value:'Uzbekistan', label:'Uzbekistan'},
{value:'Vanuatu', label:'Vanuatu'},
{value:'Vatican City State', label:'Vatican City State'},
{value:'Venezuela', label:'Venezuela'},
{value:'Vietnam', label:'Vietnam'},
{value:'Virgin Islands (Brit)', label:'Virgin Islands (Brit)'},
{value:'Virgin Islands (USA)', label:'Virgin Islands (USA)'},
{value:'Wake Island', label:'Wake Island'},
{value:'Wallis & Futana Is', label:'Wallis & Futana Is'},
{value:'Yemen', label:'Yemen'},
{value:'Zaire', label:'Zaire'},
{value:'Zambia', label:'Zambia'},
{value:'Zimbabwe', label:'Zimbabwe'},
]

export const unit = [
  {value: " BAG - BAGS" , label: " BAG - BAGS"},
  {value: "BAL - BALE", label: "BAL - BALE"},
  {value: "BDL - BUNDLES", label: "BDL - BUNDLES"},
  {value: "BKL - BUCKLES ", label: "BKL - BUCKLES"},
  {value: "BOU - BILLIONS OF UNITS", label: "BOU - BILLIONS OF UNITS"},
  {value: "BOX - BOX", label: "BOX - BOX"},
  {value: "BTL - BOTTLES", label: "BTL - BOTTLES"},
  {value: "BUN - BUNCHES", label: "BUN - BUNCHES"},
  {value: "CAN - CANS", label: "CAN - CANS"},
  {value: "CBM - CUBIC METER", label: "CBM - CUBIC METER"},
  {value: "CCM - CUBIC CENTIMETER", label: "CCM - CUBIC CENTIMETER"},
  {value: "CMS - CENTIMETER", label: "CMS - CENTIMETER"},
  {value: "CTN - CARTONS", label: "CTN - CARTONS"},
  {value: "DOZ - DOZEN", label: "DOZ - DOZEN"},
  {value: "DRM - DRUM", label: "DRM - DRUM"},
  {value: "GGR - GREAT GROSS", label: "GGR - GREAT GROSS"},
  {value: "GMS - GRAMS", label: "GMS - GRAMS"},
  {value: "GRS - GROSS", label: "GRS - GROSS"},
  {value: "GYD - GROSS YARDS", label: "GYD - GROSS YARDS"},
  {value: "KGS - KILOGRAMS", label: "KGS - KILOGRAMS"},
  {value: "KLR - KILOLITER", label: "KLR - KILOLITER"},
  {value: "KME - KILOMETRE", label: "KME - KILOMETRE"},
  {value: "MLT - MILLILITRE", label: "MLT - MILLILITRE"},
  {value: "MTR - METERS", label: "MTR - METERS"},
  {value: "NOS - NUMBERS", label: "NOS - NUMBERS"},
  {value: "PAC - PACKS", label: "PAC - PACKS"},
  {value: "PCS - PIECES", label: "PCS - PIECES"},
  {value: "PRS - PAIRS", label: "PRS - PAIRS"},
  {value: "QTL - QUINTAL", label: "QTL - QUINTAL"},
  {value: "ROL - ROLLS", label: "ROL - ROLLS"},
  {value: "SET - SETS", label: "SET - SETS"},
  {value: "SQF - SQUARE FEET", label: "SQF - SQUARE FEET"},
  {value: "SQM - SQUARE METERS", label: "SQM - SQUARE METERS"},
  {value: " TBS - TABLETS", label: "TBS - TABLETS "},
  {value: "TGM - TEN GROSS", label: "TGM - TEN GROSS"},
  {value: "THD - THOUSANDS", label: "THD - THOUSANDS"},
  {value: "TON - TONNES", label: "TON - TONNES"},
  {value: "TUB - TUBES", label: "TUB - TUBES"},
  {value: "UGS - US GALLONS", label: "UGS - US GALLONS"},
  {value: "UNT - UNITS", label: "UNT - UNITS"},
  {value: "YDS - YARDS", label: "YDS - YARDS"},
  {value: "OTH - OTHERS", label: "OTH - OTHERS"},
]

export const asset = [
  {value:'current assets', label:'current assets'},
  {value:'fixed assets', label:'fixed assets'},
  {value:'tangible assets', label:'tangible assets'},
  {value:'intangible assets', label:'intangible assets'},
  {value:'operating assets', label:' operating assets'},
  {value:'non-operating assets', label:'non-operating assets'},
]
export const income =[
  {value: "Product Sales", label: "Product Sales"},
  {value: "Sales", label: "Sales"},
  {value: "Sales - Hardware", label: "Sales - Hardware"},
  {value: "Sales - Software", label: "Sales - Software"},
  {value: "Sales - Support and Maintenance", label: "Sales - Support and Maintenance"},
  {value: "Sales of Product Income", label: "Sales of Product Income"},
];

export const currency =[
  {value:"AFN",label:"Afghan Afghani"},
  {value:"ALL",label:"Albanian Lek"},
  {value:"DZD",label:"Algerian Dinar"},
  {value:"AOA",label:"Angolan Kwanza"},
  {value:"ARS",label:"Argentine Peso"},
  {value:"AMD",label:"Armenian Dram"},
  {value:"AWG",label:"Aruban Florin"},
  {value:"AUD",label:"Australian Dollar"},
  {value:"AZN",label:"Azerbaijani Manat"},
  {value:"BSD",label:"Bahamian Dollar"},
  {value:"BHD",label:"Bahraini Dinar"},
  {value:"BDT",label:"Bangladeshi Taka"},
  {value:"BBD",label:"Barbadian Dollar"},
  {value:"BYR",label:"Belarusian Ruble"},
  {value:"BEF",label:"Belgian Franc"},
  {value:"BZD",label:"Belize Dollar"},
  {value:"BMD",label:"Bermudan Dollar"},
  {value:"BTN",label:"Bhutanese Ngultrum"},
  {value:"BTC",label:"Bitcoin"},
  {value:"BOB",label:"Bolivian Boliviano"},
  {value:"BAM",label:"Bosnia-Herzegovina Convertible Mark"},
  {value:"BWP",label:"Botswanan Pula"},
  {value:"BRL",label:"Brazilian Real"},
  {value:"GBP",label:"British Pound Sterling"},
  {value:"BND",label:"Brunei Dollar"},
  {value:"BGN",label:"Bulgarian Lev"},
  {value:"BIF",label:"Burundian Franc"},
  {value:"KHR",label:"Cambodian Riel"},
  {value:"CAD",label:"Canadian Dollar"},
  {value:"CVE",label:"Cape Verdean Escudo"},
  {value:"KYD",label:"Cayman Islands Dollar"},
  {value:"XOF",label:"CFA Franc BCEAO"},
  {value:"XAF",label:"CFA Franc BEAC"},
  {value:"XPF",label:"CFP Franc"},
  {value:"CLP",label:"Chilean Peso"},
  {value:"CNY",label:"Chinese Yuan"},
  {value:"COP",label:"Colombian Peso"},
  {value:"KMF",label:"Comorian Franc"},
  {value:"CDF",label:"Congolese Franc"},
  {value:"CRC",label:"Costa Rican ColÃ³n"},
  {value:"HRK",label:"Croatian Kuna"},
  {value:"CUC",label:"Cuban Convertible Peso"},
  {value:"CZK",label:"Czech Republic Koruna"},
  {value:"DKK",label:"Danish Krone"},
  {value:"DJF",label:"Djiboutian Franc"},
  {value:"DOP",label:"Dominican Peso"},
  {value:"XCD",label:"East Caribbean Dollar"},
  {value:"EGP",label:"Egyptian Pound"},
  {value:"ERN",label:"Eritrean Nakfa"},
  {value:"EEK",label:"Estonian Kroon"},
  {value:"ETB",label:"Ethiopian Birr"},
  {value:"EUR",label:"Euro"},
  {value:"FKP",label:"Falkland Islands Pound"},
  {value:"FJD",label:"Fijian Dollar"},
  {value:"GMD",label:"Gambian Dalasi"},
  {value:"GEL",label:"Georgian Lari"},
  {value:"DEM",label:"German Mark"},
  {value:"GHS",label:"Ghanaian Cedi"},
  {value:"GIP",label:"Gibraltar Pound"},
  {value:"GRD",label:"Greek Drachma"},
  {value:"GTQ",label:"Guatemalan Quetzal"},
  {value:"GNF",label:"Guinean Franc"},
  {value:"GYD",label:"Guyanaese Dollar"},
  {value:"HTG",label:"Haitian Gourde"},
  {value:"HNL",label:"Honduran Lempira"},
  {value:"HKD",label:"Hong Kong Dollar"},
  {value:"HUF",label:"Hungarian Forint"},
  {value:"ISK",label:"Icelandic KrÃ³na"},
  {value:"INR",label:"Indian Rupee"},
  {value:"IDR",label:"Indonesian Rupiah"},
  {value:"IRR",label:"Iranian Rial"},
  {value:"IQD",label:"Iraqi Dinar"},
  {value:"ILS",label:"Israeli New Sheqel"},
  {value:"ITL",label:"Italian Lira"},
  {value:"JMD",label:"Jamaican Dollar"},
  {value:"JPY",label:"Japanese Yen"},
  {value:"JOD",label:"Jordanian Dinar"},
  {value:"KZT",label:"Kazakhstani Tenge"},
  {value:"KES",label:"Kenyan Shilling"},
  {value:"KWD",label:"Kuwaiti Dinar"},
  {value:"KGS",label:"Kyrgystani Som"},
  {value:"LAK",label:"Laotian Kip"},
  {value:"LVL",label:"Latvian Lats"},
  {value:"LBP",label:"Lebanese Pound"},
  {value:"LSL",label:"Lesotho Loti"},
  {value:"LRD",label:"Liberian Dollar"},
  {value:"LYD",label:"Libyan Dinar"},
  {value:"LTL",label:"Lithuanian Litas"},
  {value:"MOP",label:"Macanese Pataca"},
  {value:"MKD",label:"Macedonian Denar"},
  {value:"MGA",label:"Malagasy Ariary"},
  {value:"MWK",label:"Malawian Kwacha"},
  {value:"MYR",label:"Malaysian Ringgit"},
  {value:"MVR",label:"Maldivian Rufiyaa"},
  {value:"MRO",label:"Mauritanian Ouguiya"},
  {value:"MUR",label:"Mauritian Rupee"},
  {value:"MXN",label:"Mexican Peso"},
  {value:"MDL",label:"Moldovan Leu"},
  {value:"MNT",label:"Mongolian Tugrik"},
  {value:"MAD",label:"Moroccan Dirham"},
  {value:"MZM",label:"Mozambican Metical"},
  {value:"MMK",label:"Myanmar Kyat"},
  {value:"NAD",label:"Namibian Dollar"},
  {value:"NPR",label:"Nepalese Rupee"},
  {value:"ANG",label:"Netherlands Antillean Guilder"},
  {value:"TWD",label:"New Taiwan Dollar"},
  {value:"NZD",label:"New Zealand Dollar"},
  {value:"NIO",label:"Nicaraguan CÃ³rdoba"},
  {value:"NGN",label:"Nigerian Naira"},
  {value:"KPW",label:"North Korean Won"},
  {value:"NOK",label:"Norwegian Krone"},
  {value:"OMR",label:"Omani Rial"},
  {value:"PKR",label:"Pakistani Rupee"},
  {value:"PAB",label:"Panamanian Balboa"},
  {value:"PGK",label:"Papua New Guinean Kina"},
  {value:"PYG",label:"Paraguayan Guarani"},
  {value:"PEN",label:"Peruvian Nuevo Sol"},
  {value:"PHP",label:"Philippine Peso"},
  {value:"PLN",label:"Polish Zloty"},
  {value:"QAR",label:"Qatari Rial"},
  {value:"RON",label:"Romanian Leu"},
  {value:"RUB",label:"Russian Ruble"},
  {value:"RWF",label:"Rwandan Franc"},
  {value:"SVC",label:"Salvadoran ColÃ³n"},
  {value:"WST",label:"Samoan Tala"},
  {value:"SAR",label:"Saudi Riyal"},
  {value:"RSD",label:"Serbian Dinar"},
  {value:"SCR",label:"Seychellois Rupee"},
  {value:"SLL",label:"Sierra Leonean Leone"},
  {value:"SGD",label:"Singapore Dollar"},
  {value:"SKK",label:"Slovak Koruna"},
  {value:"SBD",label:"Solomon Islands Dollar"},
  {value:"SOS",label:"Somali Shilling"},
  {value:"ZAR",label:"South African Rand"},
  {value:"KRW",label:"South Korean Won"},
  {value:"XDR",label:"Special Drawing Rights"},
  {value:"LKR",label:"Sri Lankan Rupee"},
  {value:"SHP",label:"St. Helena Pound"},
  {value:"SDG",label:"Sudanese Pound"},
  {value:"SRD",label:"Surinamese Dollar"},
  {value:"SZL",label:"Swazi Lilangeni"},
  {value:"SEK",label:"Swedish Krona"},
  {value:"CHF",label:"Swiss Franc"},
  {value:"SYP",label:"Syrian Pound"},
  {value:"STD",label:"São Tomé and Príncipe Dobra"},
  {value:"TJS",label:"Tajikistani Somoni"},
  {value:"TZS",label:"Tanzanian Shilling"},
  {value:"THB",label:"Thai Baht"},
  {value:"TOP",label:"Tongan pa'anga"},
  {value:"TTD",label:"Trinidad & Tobago Dollar"},
  {value:"TND",label:"Tunisian Dinar"},
  {value:"TRY",label:"Turkish Lira"},
  {value:"TMT",label:"Turkmenistani Manat"},
  {value:"UGX",label:"Ugandan Shilling"},
  {value:"UAH",label:"Ukrainian Hryvnia"},
  {value:"AED",label:"United Arab Emirates Dirham"},
  {value:"UYU",label:"Uruguayan Peso"},
  {value:"USD",label:"US Dollar"},
  {value:"UZS",label:"Uzbekistan Som"},
  {value:"VUV",label:"Vanuatu Vatu"},
  {value:"VEF",label:"Venezuelan BolÃ­var"},
  {value:"VND",label:"Vietnamese Dong"},
  {value:"YER",label:"Yemeni Rial"},
  {value:"ZMK",label:"Zambian Kwacha"},
  ]


  export const HotelType = [
    { value: 'Resort', label: 'Resort' },
    { value: 'Home Stay', label: 'Home Stay' },
    { value: 'Rental', label: 'Rental' },
    { value: 'Tent', label: 'Tent' }
]
  export const Bed = [
    { value: 'Single', label: 'Single' },
    { value: 'Queen', label: 'Queen' },
    { value: 'King', label: 'King' },
    { value: 'Twin', label: 'Twin' },
    { value: 'Double', label: 'Double' },
    { value: 'Triple', label: 'Triple' },
    { value: 'Family', label: 'Family' },
    { value: 'Extra Bed', label: 'Extra Bed' },
]
  export const Meal = [
    { value: 'Room Only', label: 'Room Only' },
    { value: 'Bed and Breakfast', label: 'Bed and Breakfast' },
    { value: 'Half Board', label: 'Half Board' },
    { value: 'Full Board', label: 'Full Board' },
    { value: 'All Inclusive(Breakfast,Lunch,Dinner & Drinks)', label: 'All Inclusive(Breakfast,Lunch,Dinner & Drinks)' }
]
  export const Occupiency = [
    { value: 'Single Room', label: 'Single Room' },
    { value: 'Double Room', label: 'Double Room' },
    { value: 'Triple room', label: 'Triple room' },
    { value: 'Family Room', label: 'Family Room' },
    { value: 'One Bed Room', label: 'One Bed Room' },
    { value: 'Two Bed Room', label: 'Two Bed Room' },
    { value: 'Studio', label: 'Studio' },
]



  export const RegistrationType =[
    {value:"Registered",label:"Registered"},
    {value:"Un-Registered",label:"Un-Registered"},
    {value:"Overseas",label:"Overseas"},
    {value:"Special Economic Zone",label:"Special Economic Zone"},
    {value:"Deemed Export",label:"Deemed Export"},
  ]

 export const gender = [
    { value: 'Male', label: 'Male' },
    { value: 'Female', label: 'Female' },
    { value: 'Others', label: 'Others' }
  ];
  export const Terms =[
    {value:"Net 5",label:"Net 5"},
    {value:"Net 15",label:"Net 15"},
    {value:"Net 30",label:"Net 30"},
    {value:"Net 48",label:"Net 48"},
  ]
export const Relationship=[
  {value:"Spouse",label:"Spouse"},
  {value:"Son",label:"Son"},
  {value:"Daughter",label:"Daughter"},
  {value:"Guardian",label:"Guardian"},
  {value:"Friend",label:"Friend"},
 
]
export const bloodgroup = [
  {value: "A +ve", label : "A +ve"},
  {value: "A -ve", label : "A -ve"},
  {value: "B +ve", label : "B +ve"},
  {value: "B -ve", label : "B -ve"},
  {value: "AB +ve", label : "AB +ve"},
  {value: "AB -ve", label : "AB -ve"},
  {value: "O +ve", label : "O +ve"},
  {value: "O -ve", label : "O -ve"},
]


const Asset= [
  { value: "Current Asset", label: "Current Asset" },
  { value: "Other Current Asset", label: "Other Current Asset" },
  { value: "Cash", label: "Cash" },
  { value: "Bank", label: "Bank" },
  { value: "Fixed Asset", label: "Fixed Asset" },
  { value: "Stock", label: "Stock" },
  { value: "Payment Clearing", label: "Payment Clearing" },
 
  
];

const Liability = [
  { value: "Other Current Liability", label: "Other Current Liability" },
  { value: "Credit Card", label: "Credit Card" },
  { value: "Long Term Liability", label: "Long Term Liability" },
  { value: "Other Liability", label: "Other Liability" },
  { value: "Oversease Tax Payable", label: "Oversease Tax Payable" },
 
  
];
const Equilty = [
  { value: "Equilty", label: "Equilty" },
 
 
];
const Income = [
  { value: "Income", label: "Income" },
  { value: "Other Income", label: "Other Income"}
 
];
const Expence = [
  { value: "Expence", label: "Expence" },
  { value: "Cost of Goods Sold", label: "Cost of Goods Sold"},
  { value: "Other Expence", label: "Other Expence"}
 
];

export const groupedOptions = [
  {
    label: "Asset",
    options: Asset
  },
  {
    label: "Liability",
    options: Liability
  },
  {
    label: "Equilty",
    options: Equilty
  },
  {
    label: "Income",
    options: Income
  },
  
  {
    label: "Expence",
    options: Expence
  },
];

export const filterOptions = [
  {
    label: "All Account",
    value: ""
  },
  {
    label: "Asset",
    options: Asset
  },
  {
    label: "Liability",
    options: Liability
  },
  {
    label: "Equilty",
    options: Equilty
  },
  {
    label: "Income",
    options: Income
  },
  
  {
    label: "Expence",
    options: Expence
  },
];

 export const account=[
        { value:"",label:"All Accounts"},
        { value:"Others",label:"Active Accounts"},
        { value:"Hotel",label:"Inactive Accounts"},
        { value:"Flight",label:"Asset Accounts"},
        { value:"Visa",label:"Liability Accounts"},
        { value:"Insurance",label:"Equity Accounts"},
        { value:"Insurance",label:"Income Accounts"},
        { value:"Insurance",label:"Expense Accounts"}
];
export const asset1 = [
  {value:'current assets', label:'current assets'},
  {value:'fixed assets', label:'fixed assets'},
  {value:'tangible assets', label:'tangible assets'},
  {value:'intangible assets', label:'intangible assets'},
  {value:'operating assets', label:' operating assets'},
  {value:'non-operating assets', label:'non-operating assets'},
]





export const tax = [
  {value:'12', label:'12%'},
  {value:'18', label:'18%'},
  {value:'28', label:'28%'},
]
export const Active = [
  { value: "", label: "All" },
  { value: "Active", label: "Active" },
  { value: "Inactive", label: "Inactive"}
 
];
export const categaroy = [
  {value: "Category" , label: "Category"},
  {value: "Sub-Category", label: "Sub-Category"},
]
export const PaymentMode = [
  {value: "Cash" , label: "Cash"},
  {value: "DD" , label: "DD"},
  {value: "Cheque", label: "Cheque"},
  {value: "Net-Banking", label: "Net-Banking"},
]
export default {PaymentMode,categaroy,Meal,Occupiency,Bed,Active,tax,asset1,country,currency,RegistrationType,Terms,gender,Relationship,bloodgroup,groupedOptions,HotelType,account,filterOptions,unit,income,asset}
