import React from "react";
import * as Icon from "react-feather";
const navigationConfig = [
  // {
  //   id: "dashboard",
  //   title: "Dashboard",
  //   type: "collapse",
  //   icon: <Icon.Home size={20} />,
  //   badge: "warning",
  //   badgeText: "2",
  //   children: [
  //     {
  //       id: "analyticsDash",
  //       title: "Analytics",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/",
  //     },
  //     {
  //       id: "eCommerceDash",
  //       title: "eCommerce",
  //       type: "item",
  //       icon: <Icon.Circle size={12} />,
  //       permissions: ["admin"],
  //       navLink: "/ecommerce-dashboard",
  //     },
  //   ],
  // },
  {
    id: "Dashboard",
    title: "Dashboard",
    type: "item",
    icon: <Icon.Grid size={20} />,
    navLink: "/profile",
  },
  {
    id: "DSR",
    title: "DSR",
    type: "collapse",
    icon: <Icon.Layers size={20} />,
    children: [
      {
        id: "CDSR",
        title: "DSR",
        type: "item",
        permissions: ["admin", "editor"],
        navLink: "/dsr",
      },
      {
        id: "MICE",
        title: "MICE",
        type: "item",
        permissions: ["admin", "editor"],
        navLink: "/mice",
      },
      {
        id: "My Package",
        title: "Package",
        type: "item",
        permissions: ["admin", "editor"],
        navLink: "/",
      },
    ],
  },
  {
    id: "Customers",
    title: "Customer",
    type: "collapse",
    icon: <Icon.Users size={20}/>,
    children: [
      {
        id: "Corporates",
        title: "Corporate",
        type: "item",
        permissions: ["admin", "editor"],
        navLink: "/customer/corporate",
      },
      {
        id: "Individuals",
        title: "Individual",
        type: "item",
        permissions: ["admin", "editor"],
        navLink: "/customer/induvidual",
      }
    ],
  },
  {
    id: "My Sales",
    title: "Sales",
    type: "collapse",
    icon: <Icon.ShoppingBag size={20} />,
    children: [
      {
        id: "Quotes",
        title: "Quotation",
        type: "item",
        permissions: ["admin", "editor"],
        navLink: "/sales/quotation",
      },
      {
        id: "Pros",
        title: "Pro-Forma",
        type: "item",
        permissions: ["admin", "editor"],
        navLink: "/sales/proforma",
      },
      {
        id: "Invoices",
        title: "Invoice",
        type: "item",
        permissions: ["admin", "editor"],
        navLink: "/sales/invoice",
      },
      {
        id: "CreditNotes",
        title: "Credit Note",
        type: "item",
        permissions: ["admin", "editor"],
        navLink: "/",
      },
      {
        id: "Paymets",
        title: "Payment Received",
        type: "item",
        permissions: ["admin", "editor"],
        navLink: "/sales/paymentRecived",
      }
    ],
  },
  {
    id: "Purchase",
    title: "Purchases",
    type: "collapse",
    icon: <Icon.CreditCard size={20} />,
    children: [
      {
        id: "supply",
        title: "Supplier",
        type: "item",
        permissions: ["admin", "editor"],
        navLink: "/purchase/supplier",
      },
      {
        id: "Expense",
        title: "Expenses",
        type: "item",
        permissions: ["admin", "editor"],
        navLink: "/purchase/Expenses",
      },
      {
        id: "Debit",
        title: "Debit Note",
        type: "item",
        permissions: ["admin", "editor"],
        navLink: "/",
      },
      {
        id: "Bill",
        title: "Bills",
        type: "item",
        permissions: ["admin", "editor"],
        navLink: "/purchase/bill",
      },
      {
        id: "modePayment",
        title: "Payment Made",
        type: "item",
        permissions: ["admin", "editor"],
        navLink: "/purchase/paymentMade",
      },
    ],
  },
  {
    id: "ProductAndServices",
    title: "Product & Services",
    type: "collapse",
    icon: <Icon.Package size={20} />,
    children: [
      {
        id: "inventory",
        title: "Inventory",
        type: "item",
        permissions: ["admin", "editor"],
        navLink: "/productservices/inventory",
      },
      {
        id: "Noninventory",
        title: "Non-Inventory",
        type: "item",
        permissions: ["admin", "editor"],
        navLink: "/productservices/nonInventory",
      },
      {
        id: "service",
        title: "Services",
        type: "item",
        permissions: ["admin", "editor"],
        navLink: "/productservices/servicess",
      },
    ],
  },
  {
    id: "Account",
    title: "Accountant",
    type: "collapse",
    icon: <Icon.Edit3 size={20} />,
    children: [
      {
        id: "charts",
        title: "Charts of account",
        type: "item",
        permissions: ["admin", "editor"],
        navLink: "/accountant/ChartsOfAccount",
      },
      {
        id: "Tax",
        title: "Tax Master",
        type: "item",
        permissions: ["admin", "editor"],
        navLink: "/",
      },
      {
        id: "Paymentmasters",
        title: "Payment Master",
        type: "item",
        permissions: ["admin", "editor"],
        navLink: "/",
      },
    ],
  },
  {
    id: "Report",
    title: "Reports",
    type: "item",
    icon: <Icon.FileText size={20} />,
    permissions: ["admin", "editor"],
    navLink: "/",
  },
  {
    id: "hrManagement",
    title: "Hr. Management",
    type: "item",
    icon: <Icon.UserCheck size={20} />,
    permissions: ["admin", "editor"],
    navLink: "/employee",
  },
];
export default navigationConfig;