export const data = [
  {
    id: "1",
    name: "name",
    company: "company",
    contry: "contry",
    state: "state",
  },
  {
    id: "2",
    name: "name",
    company: "company1",
    contry: "contry",
    state: "state",
  },
  {
    id: "3",
    name: "name",
    company: "company2",
    contry: "contry",
    state: "state",
  },
  {
    id: "4",
    name: "name",
    company: "company",
    contry: "contry",
    state: "state",
  },
  {
    id: "5",
    name: "name",
    company: "company1",
    contry: "contry",
    state: "state",
  },
  {
    id: "6",
    name: "name",
    company: "company2",
    contry: "contry",
    state: "state",
  },
  {
    id: "7",
    name: "name",
    company: "company",
    contry: "contry",
    state: "state",
  },
  {
    id: "8",
    name: "name",
    company: "company1",
    contry: "contry",
    state: "state",
  },
  {
    id: "9",
    name: "name",
    company: "company2",
    contry: "contry",
    state: "state",
  },
  {
    id: "10",
    name: "name",
    company: "company",
    contry: "contry",
    state: "state",
  },
  {
    id: "11",
    name: "name",
    company: "company1",
    contry: "contry",
    state: "state",
  },
  {
    id: "12",
    name: "name",
    company: "company2",
    contry: "contry",
    state: "state",
  },
  {
    id: "13",
    name: "name",
    company: "company",
    contry: "contry",
    state: "state",
  },
  {
    id: "14",
    name: "name",
    company: "company1",
    contry: "contry",
    state: "state",
  },
  {
    id: "15",
    name: "name",
    company: "company2",
    contry: "contry",
    state: "state",
  },
  {
    id: "16",
    name: "name",
    company: "company",
    contry: "contry",
    state: "state",
  },
  {
    id: "17",
    name: "name",
    company: "company1",
    contry: "contry",
    state: "state",
  },
  {
    id: "18",
    name: "name",
    company: "company2",
    contry: "contry",
    state: "state",
  },
  {
    id: "19",
    name: "name",
    company: "company",
    contry: "contry",
    state: "state",
  },
  {
    id: "20",
    name: "name",
    company: "company1",
    contry: "contry",
    state: "state",
  },
];
